### ISSUE TITLE
Difference from STARKs

### ISSUE THREAD

**Issue by paulmillr** [ebfull/halo#12]
My understanding is that zk-STARKs also require no trusted setup.

How is Halo different from STARKs? How is it better?

**Comment by chejazi** [comment]
Per the abstract (emphasis mine):
> All previously known realizations of **recursive** proof composition have required a trusted setup and cycles of expensive pairing-friendly elliptic curves.

https://electriccoin.co/wp-content/uploads/2019/09/Halo.pdf

**Comment by ebfull** [comment]
The paper will be updated with some information related to this question.
