### ISSUE TITLE
Is there anything wrong in `s` vector  in section 3.1 of Halo paper?

### ISSUE THREAD

**Issue by 3for** [ebfull/halo#23]
![image](https://user-images.githubusercontent.com/30716372/65701871-a8aa9f00-e0b4-11e9-90c7-432cdfd8b14e.png)
I think the `s` vector should be shown as below:
![image](https://user-images.githubusercontent.com/30716372/65702100-02ab6480-e0b5-11e9-9979-7cce9d0186db.png)

**Comment by ebfull** [comment]
It's possible this is backwards, but...

u_j is the challenge for the jth round starting with u_k and going down to u_1. This means that the first elements of the s vector (corresponding to the lower side of the beginning rounds) will be multiplied by the inverses. If I'm right, our paper at least must be updated to clarify this ordering. (I am trying to replicate the ordering described [here.](https://doc-internal.dalek.rs/bulletproofs/inner_product_proof/index.html))

**Comment by 3for** [comment]
@ebfull The curve for EC0 and EC1 (y^2=x^3+5 and y^2=x^3+7, both with different finite field `p` from  `secp224k1` and `secp256k1`.)
It seemed that EC0 and EC1 are new pairing-friendly curves? Is  there a corresponding paper for them?

**Comment by ebfull** [comment]
We're actually changing to a different curve cycle in an update to our paper, but these are not intended to be pairing-friendly cycles. We're avoiding pairings entirely.

**Comment by 3for** [comment]
Wow, expecting the update so much.

**Comment by daira** [comment]
The ordering in the paper is consistent with https://doc-internal.dalek.rs/bulletproofs/inner_product_proof/index.html , so this can be closed.
